sudo: required
service:
 - docker
before_install:
  - docker build -t senthilrajavelu1983/travisdoc:v3.0 .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker senthilrajavelu1983/travisdoc:v3.0
notifications:
 email:
   recipients:
     - senthilrajavelu1983@gmail.com
   on_success: always
   on_failure: always
